// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI operations (migrate, db push, etc.) need a direct (non-pooled)
  // connection because PgBouncer's transaction pooling mode doesn't
  // support the prepared statements/advisory locks Prisma Migrate uses.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
