// Vietnam administrative data (63 provinces, pre-2025-merger), tỉnh/thành -> quận/huyện.
// Source: user-supplied reference list (vietnam-tinh-huyen.md).
export const VIETNAM_PROVINCES: Record<string, string[]> = {
  "An Giang": ["Long Xuyên", "Châu Đốc", "An Phú", "Tân Châu", "Phú Tân", "Châu Phú", "Tịnh Biên", "Tri Tôn", "Châu Thành", "Chợ Mới", "Thoại Sơn"],
  "Bà Rịa – Vũng Tàu": ["Vũng Tàu", "Bà Rịa", "Châu Đức", "Xuyên Mộc", "Long Điền", "Đất Đỏ", "Tân Thành", "Côn Đảo"],
  "Bắc Giang": ["Bắc Giang", "Yên Thế", "Tân Yên", "Lạng Giang", "Lục Nam", "Lục Ngạn", "Sơn Động", "Yên Dũng", "Việt Yên", "Hiệp Hòa"],
  "Bắc Kạn": ["Bắc Kạn", "Pác Nặm", "Ba Bể", "Ngân Sơn", "Bạch Thông", "Chợ Đồn", "Na Rì", "Chợ Mới"],
  "Bạc Liêu": ["Bạc Liêu", "Hồng Dân", "Phước Long", "Vĩnh Lợi", "Giá Rai", "Đông Hải", "Hòa Bình"],
  "Bắc Ninh": ["Bắc Ninh", "Yên Phong", "Quế Võ", "Tiên Du", "Từ Sơn", "Thuận Thành", "Gia Bình", "Lương Tài"],
  "Bến Tre": ["Bến Tre", "Châu Thành", "Chợ Lách", "Mỏ Cày Nam", "Mỏ Cày Bắc", "Giồng Trôm", "Bình Đại", "Ba Tri", "Thạnh Phú"],
  "Bình Định": ["Quy Nhơn", "An Lão", "Hoài Ân", "Hoài Nhơn", "Phù Mỹ", "Vĩnh Thạnh", "Tây Sơn", "Phù Cát", "An Nhơn", "Tuy Phước", "Vân Canh"],
  "Bình Dương": ["Thủ Dầu Một", "Bến Cát", "Dĩ An", "Thuận An", "Tân Uyên", "Phú Giáo", "Dầu Tiếng", "Bàu Bàng"],
  "Bình Phước": ["Đồng Xoài", "Bình Long", "Phước Long", "Lộc Ninh", "Bù Đốp", "Hớn Quản", "Đồng Phú", "Bù Gia Mập", "Chơn Thành", "Phú Riềng"],
  "Bình Thuận": ["Phan Thiết", "La Gi", "Tuy Phong", "Bắc Bình", "Hàm Thuận Bắc", "Hàm Thuận Nam", "Tánh Linh", "Đức Linh", "Hàm Tân", "Phú Quý"],
  "Cà Mau": ["Cà Mau", "U Minh", "Thới Bình", "Trần Văn Thời", "Cái Nước", "Đầm Dơi", "Năm Căn", "Phú Tân", "Ngọc Hiển"],
  "Cần Thơ": ["Ninh Kiều", "Ô Môn", "Bình Thuỷ", "Cái Răng", "Thốt Nốt", "Vĩnh Thạnh", "Cờ Đỏ", "Phong Điền", "Thới Lai"],
  "Cao Bằng": ["Cao Bằng", "Bảo Lâm", "Bảo Lạc", "Hà Quảng", "Trùng Khánh", "Hạ Lang", "Quảng Uyên", "Phục Hòa", "Hòa An", "Nguyên Bình", "Thạch An"],
  "Đà Nẵng": ["Hải Châu", "Thanh Khê", "Sơn Trà", "Ngũ Hành Sơn", "Liên Chiểu", "Cẩm Lệ", "Hoà Vang", "Hoàng Sa"],
  "Đắk Lắk": ["Buôn Ma Thuột", "Ea H'leo", "Ea Súp", "Krông Búk", "Krông Năng", "Ea Kar", "M'Đrắk", "Krông Bông", "Krông Pắc", "Krông A Na", "Lắk", "Cư Kuin", "Buôn Đôn", "Cư M'Gar"],
  "Đắk Nông": ["Gia Nghĩa", "Đắk Glong", "Cư Jút", "Đắk Mil", "Krông Nô", "Đắk Song", "Đắk R'Lấp", "Tuy Đức"],
  "Điện Biên": ["Điện Biên Phủ", "Mường Lay", "Mường Nhé", "Mường Chà", "Tủa Chùa", "Tuần Giáo", "Điện Biên", "Điện Biên Đông", "Nậm Pồ"],
  "Đồng Nai": ["Biên Hòa", "Long Khánh", "Tân Phú", "Định Quán", "Xuân Lộc", "Long Thành", "Nhơn Trạch", "Trảng Bom", "Thống Nhất", "Cẩm Mỹ", "Vĩnh Cửu"],
  "Đồng Tháp": ["Cao Lãnh", "Sa Đéc", "Hồng Ngự", "Tân Hồng", "Hồng Ngự (huyện)", "Tam Nông", "Tháp Mười", "Cao Lãnh (huyện)", "Lấp Vò", "Lai Vung", "Châu Thành"],
  "Gia Lai": ["Pleiku", "An Khê", "Ayun Pa", "KBang", "Đak Đoa", "Chư Păh", "Ia Grai", "Mang Yang", "Kông Chro", "Đức Cơ", "Chư Prông", "Chư Sê", "Đak Pơ", "Ia Pa", "Krông Pa", "Phú Thiện", "Chư Pưh"],
  "Hà Giang": ["Hà Giang", "Đồng Văn", "Mèo Vạc", "Yên Minh", "Quản Bạ", "Vị Xuyên", "Bắc Mê", "Hoàng Su Phì", "Xín Mần", "Bắc Quang", "Quang Bình"],
  "Hà Nam": ["Phủ Lý", "Duy Tiên", "Kim Bảng", "Thanh Liêm", "Bình Lục", "Lý Nhân"],
  "Hà Nội": ["Ba Đình", "Hoàn Kiếm", "Hai Bà Trưng", "Đống Đa", "Tây Hồ", "Cầu Giấy", "Thanh Xuân", "Hoàng Mai", "Long Biên", "Hà Đông", "Bắc Từ Liêm", "Nam Từ Liêm", "Sóc Sơn", "Đông Anh", "Gia Lâm", "Đan Phượng", "Hoài Đức", "Quốc Oai", "Thạch Thất", "Chương Mỹ", "Thanh Oai", "Thường Tín", "Phú Xuyên", "Ứng Hòa", "Mỹ Đức", "Mê Linh", "Ba Vì", "Phúc Thọ"],
  "Hà Tĩnh": ["Hà Tĩnh", "Hồng Lĩnh", "Hương Sơn", "Đức Thọ", "Vũ Quang", "Nghi Xuân", "Can Lộc", "Hương Khê", "Thạch Hà", "Cẩm Xuyên", "Kỳ Anh", "Lộc Hà", "Kỳ Anh (thị xã)"],
  "Hải Dương": ["Hải Dương", "Chí Linh", "Nam Sách", "Kinh Môn", "Kim Thành", "Thanh Hà", "Cẩm Giàng", "Bình Giang", "Gia Lộc", "Tứ Kỳ", "Ninh Giang", "Thanh Miện"],
  "Hải Phòng": ["Hồng Bàng", "Ngô Quyền", "Lê Chân", "Hải An", "Kiến An", "Đồ Sơn", "Dương Kinh", "Thuỷ Nguyên", "An Dương", "An Lão", "Kiến Thuỵ", "Tiên Lãng", "Vĩnh Bảo", "Cát Hải", "Bạch Long Vĩ"],
  "Hậu Giang": ["Vị Thanh", "Ngã Bảy", "Châu Thành", "Châu Thành A", "Phụng Hiệp", "Vị Thuỷ", "Long Mỹ", "Long Mỹ (thị xã)"],
  "Hoà Bình": ["Hòa Bình", "Đà Bắc", "Mai Châu", "Tân Lạc", "Lạc Sơn", "Kim Bôi", "Cao Phong", "Lương Sơn", "Lạc Thủy", "Yên Thủy"],
  "Hưng Yên": ["Hưng Yên", "Mỹ Hào", "Ân Thi", "Khoái Châu", "Kim Động", "Tiên Lữ", "Phù Cừ", "Văn Lâm", "Văn Giang", "Yên Mỹ"],
  "Khánh Hòa": ["Nha Trang", "Cam Ranh", "Vạn Ninh", "Ninh Hòa", "Diên Khánh", "Khánh Vĩnh", "Khánh Sơn", "Cam Lâm", "Trường Sa"],
  "Kiên Giang": ["Rạch Giá", "Hà Tiên", "Kiên Lương", "Hòn Đất", "Tân Hiệp", "Châu Thành", "Giồng Riềng", "Gò Quao", "An Biên", "An Minh", "Vĩnh Thuận", "Phú Quốc", "Kiên Hải", "U Minh Thượng", "Giang Thành"],
  "Kon Tum": ["Kon Tum", "Đắk Glei", "Ngọc Hồi", "Đắk Tô", "Kon Plông", "Kon Rẫy", "Đắk Hà", "Sa Thầy", "Tu Mơ Rông", "Ia H'Drai"],
  "Lai Châu": ["Lai Châu", "Tam Đường", "Mường Tè", "Sìn Hồ", "Phong Thổ", "Than Uyên", "Tân Uyên", "Nậm Nhùn"],
  "Lâm Đồng": ["Đà Lạt", "Bảo Lộc", "Đam Rông", "Lạc Dương", "Lâm Hà", "Đơn Dương", "Đức Trọng", "Di Linh", "Bảo Lâm", "Đạ Huoai", "Đạ Tẻh", "Cát Tiên"],
  "Lạng Sơn": ["Lạng Sơn", "Tràng Định", "Bình Gia", "Văn Lãng", "Cao Lộc", "Văn Quan", "Bắc Sơn", "Hữu Lũng", "Chi Lăng", "Lộc Bình", "Đình Lập"],
  "Lào Cai": ["Lào Cai", "Bát Xát", "Mường Khương", "Si Ma Cai", "Bắc Hà", "Bảo Thắng", "Bảo Yên", "Sa Pa", "Văn Bàn"],
  "Long An": ["Tân An", "Kiến Tường", "Tân Hưng", "Vĩnh Hưng", "Mộc Hóa", "Tân Thạnh", "Thạnh Hóa", "Đức Huệ", "Đức Hòa", "Bến Lức", "Thủ Thừa", "Tân Trụ", "Cần Đước", "Cần Giuộc", "Châu Thành"],
  "Nam Định": ["Nam Định", "Mỹ Lộc", "Vụ Bản", "Ý Yên", "Nghĩa Hưng", "Nam Trực", "Trực Ninh", "Xuân Trường", "Giao Thủy", "Hải Hậu"],
  "Nghệ An": ["Vinh", "Cửa Lò", "Thái Hòa", "Hoàng Mai", "Quỳ Hợp", "Quỳ Châu", "Quế Phong", "Tương Dương", "Kỳ Sơn", "Con Cuông", "Tân Kỳ", "Anh Sơn", "Đô Lương", "Thanh Chương", "Nghi Lộc", "Nam Đàn", "Hưng Nguyên", "Diễn Châu", "Yên Thành", "Quỳnh Lưu"],
  "Ninh Bình": ["Ninh Bình", "Tam Điệp", "Nho Quan", "Gia Viễn", "Hoa Lư", "Yên Mô", "Yên Khánh", "Kim Sơn"],
  "Ninh Thuận": ["Phan Rang-Tháp Chàm", "Bác Ái", "Ninh Sơn", "Ninh Hải", "Ninh Phước", "Thuận Nam", "Thuận Bắc"],
  "Phú Thọ": ["Việt Trì", "Phú Thọ", "Đoan Hùng", "Hạ Hòa", "Thanh Ba", "Cẩm Khê", "Yên Lập", "Tam Nông", "Lâm Thao", "Phù Ninh", "Thanh Sơn", "Thanh Thủy", "Tân Sơn"],
  "Phú Yên": ["Tuy Hòa", "Sông Cầu", "Đồng Xuân", "Tuy An", "Sơn Hòa", "Sông Hinh", "Tây Hòa", "Phú Hòa", "Đông Hòa"],
  "Quảng Bình": ["Đồng Hới", "Ba Đồn", "Tuyên Hóa", "Minh Hóa", "Quảng Trạch", "Bố Trạch", "Quảng Ninh", "Lệ Thủy"],
  "Quảng Nam": ["Tam Kỳ", "Hội An", "Tây Giang", "Đông Giang", "Đại Lộc", "Điện Bàn", "Duy Xuyên", "Quế Sơn", "Nam Giang", "Phước Sơn", "Hiệp Đức", "Thăng Bình", "Tiên Phước", "Bắc Trà My", "Nam Trà My", "Núi Thành", "Phú Ninh", "Nông Sơn"],
  "Quảng Ngãi": ["Quảng Ngãi", "Đức Phổ", "Ba Tơ", "Sơn Hà", "Sơn Tây", "Minh Long", "Nghĩa Hành", "Mộ Đức", "Tư Nghĩa", "Sơn Tịnh", "Bình Sơn", "Trà Bồng", "Lý Sơn", "Tây Trà"],
  "Quảng Ninh": ["Hạ Long", "Móng Cái", "Cẩm Phả", "Uông Bí", "Đông Triều", "Quảng Yên", "Hoành Bồ", "Bình Liêu", "Tiên Yên", "Đầm Hà", "Hải Hà", "Ba Chẽ", "Vân Đồn", "Cô Tô"],
  "Quảng Trị": ["Đông Hà", "Quảng Trị", "Vĩnh Linh", "Hướng Hóa", "Gio Linh", "Đakrông", "Cam Lộ", "Triệu Phong", "Hải Lăng", "Cồn Cỏ"],
  "Sóc Trăng": ["Sóc Trăng", "Châu Thành", "Kế Sách", "Mỹ Tú", "Cù Lao Dung", "Long Phú", "Mỹ Xuyên", "Ngã Năm", "Thạnh Trị", "Vĩnh Châu", "Trần Đề"],
  "Sơn La": ["Sơn La", "Quỳnh Nhai", "Thuận Châu", "Mường La", "Bắc Yên", "Phù Yên", "Mộc Châu", "Yên Châu", "Mai Sơn", "Sông Mã", "Sốp Cộp", "Vân Hồ"],
  "Tây Ninh": ["Tây Ninh", "Tân Biên", "Tân Châu", "Dương Minh Châu", "Châu Thành", "Hòa Thành", "Gò Dầu", "Bến Cầu", "Trảng Bàng"],
  "Thái Bình": ["Thái Bình", "Quỳnh Phụ", "Hưng Hà", "Đông Hưng", "Thái Thụy", "Tiền Hải", "Kiến Xương", "Vũ Thư"],
  "Thái Nguyên": ["Thái Nguyên", "Sông Công", "Phổ Yên", "Định Hóa", "Phú Lương", "Đồng Hỷ", "Võ Nhai", "Đại Từ", "Phú Bình"],
  "Thanh Hóa": ["Thanh Hóa", "Bỉm Sơn", "Sầm Sơn", "Mường Lát", "Quan Hóa", "Bá Thước", "Quan Sơn", "Lang Chánh", "Ngọc Lặc", "Cẩm Thủy", "Thạch Thành", "Hà Trung", "Vĩnh Lộc", "Yên Định", "Thọu Xuân", "Thường Xuân", "Triệu Sơn", "Thiệu Hóa", "Hoằng Hóa", "Hậu Lộc", "Nga Sơn", "Như Xuân", "Như Thanh", "Nông Cống", "Đông Sơn", "Quảng Xương", "Tĩnh Gia"],
  "Thừa Thiên Huế": ["Huế", "Phong Điền", "Quảng Điền", "Hương Trà", "Phú Vang", "Hương Thủy", "Phú Lộc", "Nam Đông", "A Lưới"],
  "Tiền Giang": ["Mỹ Tho", "Gò Công", "Cai Lậy", "Tân Phước", "Cái Bè", "Cai Lậy (huyện)", "Châu Thành", "Chợ Gạo", "Gò Công Tây", "Gò Công Đông", "Tân Phú Đông"],
  "TP. Hồ Chí Minh": ["Quận 1", "Quận 3", "Quận 4", "Quận 5", "Quận 6", "Quận 7", "Quận 8", "Quận 10", "Quận 11", "Quận 12", "Bình Thạnh", "Gò Vấp", "Phú Nhuận", "Tân Bình", "Tân Phú", "Bình Tân", "Thủ Đức", "Bình Chánh", "Hóc Môn", "Củ Chi", "Nhà Bè", "Cần Giờ"],
  "Trà Vinh": ["Trà Vinh", "Càng Long", "Cầu Kè", "Tiểu Cần", "Châu Thành", "Cầu Ngang", "Trà Cú", "Duyên Hải", "Duyên Hải (thị xã)"],
  "Tuyên Quang": ["Tuyên Quang", "Lâm Bình", "Na Hang", "Chiêm Hóa", "Hàm Yên", "Yên Sơn", "Sơn Dương"],
  "Vĩnh Long": ["Vĩnh Long", "Long Hồ", "Mang Thít", "Vũng Liêm", "Tam Bình", "Bình Minh", "Trà Ôn", "Bình Tân"],
  "Vĩnh Phúc": ["Vĩnh Yên", "Phúc Yên", "Lập Thạch", "Sông Lô", "Tam Dương", "Tam Đảo", "Bình Xuyên", "Yên Lạc", "Vĩnh Tường"],
  "Yên Bái": ["Yên Bái", "Nghĩa Lộ", "Lục Yên", "Văn Yên", "Mù Cang Chải", "Trấn Yên", "Trạm Tấu", "Văn Chấn", "Yên Bình"],
};
